# Generated by Django 6.1.1 on 2026-09-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='complainant_name',
            field=models.CharField(default='Anonymous', max_length=150),
        ),
    ]
